### ISSUE TITLE
When a song is finished scrobbling, the application crashes.

### ISSUE THREAD

**Issue by WCBROW01** [69/fmcord#4]
I get this error:
```
events.js:183
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'name' of undefined
    at processLastPlay (/home/will/fmcord/node_modules/lastfm/lib/lastfm/recenttracks-stream.js:98:45)
    at module.exports.handleSuccess (/home/will/fmcord/node_modules/lastfm/lib/lastfm/recenttracks-stream.js:61:9)
    at emitOne (events.js:116:13)
    at module.exports.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/will/fmcord/node_modules/lastfm/lib/lastfm/lastfm-request.js:123:14)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by 69** [comment]
this was an issue with the lastfm library, which i believe was fixed by them
